### ISSUE TITLE
Windows Support?  What would it take?

### ISSUE THREAD

**Issue by einsty** [agiledivider/vagrant-hostsupdater#11]
Thanks so much for this little plugin.  SO far it is working like a champ for those in our team who are on *nix operating systems but the Windows folks are left hanging in the wind.

I might be inclinded to help out on this task but not totally familiar w/ ruby, would this be as easy as extracting the path that is used in the .rb file several times into a variable that is determined in some fashion?  Or is there more to it?

**Comment by marcovtwout** [comment]
Isn't there a nice way to automatically prompt the user for administrator permissions when attempting to write to the hosts file?

**Comment by rocpatel** [comment]
It looks like there are 2 issues here.  The first is that `File.writable?` is not accurately reflecting that the user does not have permission to the file.  This looks like a bug with ruby https://bugs.ruby-lang.org/issues/4712.  Also, was wondering if we could just use the `runas` command for windows.  I can submit a PR that gets around the `File.writable?` bug by using `sudo` when the platform is windows, and change the `sudo` method to use `runas` for windows.
