### ISSUE TITLE
Excessive terminal output?

### ISSUE THREAD

**Issue by tyler36** [agiledivider/vagrant-hostsupdater#158]
Updated to v1.1.1 this morning and my console repeat the following 297 times
```
...
==> homestead-7: [vagrant-hostsupdater]   found entry for: 192.168.10.10 homestead
==> homestead-7: [vagrant-hostsupdater]   found entry for: 192.168.10.10 homestead
==> homestead-7: [vagrant-hostsupdater]   found entry for: 192.168.10.10 homestead
==> homestead-7: [vagrant-hostsupdater]   found entry for: 192.168.10.10 homestead
...
```

Downgraded to v1.0.2 and it displayed once again (as expected)

OS: Win10
Vagrant: 2.0.3
vagrant-hostsupdater: 1.0.2

**Comment by cgsmith** [comment]
That is very excessive. I'll get a fix in the works.

**Comment by tyler36** [comment]
I have 5 machines in my YAML too. The first time I booted up, it was that x5. I thought it might be a mulple machine issues but when I changed it to only 1, it was still an issue.

**Comment by Jonanien** [comment]
This still seems to be an issue
![image](https://user-images.githubusercontent.com/7956514/110803119-26e60b80-827f-11eb-8093-321c628cc95e.png)

**Comment by tyler36** [comment]
Closing as "wontfix".
