### ISSUE TITLE
vagrant-hostsupdater is missing

### ISSUE THREAD

**Issue by harsxv** [agiledivider/vagrant-hostsupdater#168]
Hello, last night my vagrant machine in Digitalocean running well.
But, this morning when I try to `vagrant-ssh`, I got error messages: 

 > [harsxv@heiften ELK-stack-Digitalocean]$ vagrant ssh
 > Vagrant failed to initialize at a very early stage:
 > 
 > vagrant-hostsupdater missing, please install the plugin with this command:
 > vagrant plugin install vagrant-hostsupdater
 >
 > [harsxv@heiften ELK-stack-Digitalocean]$ vagrant plugin install vagrant-hostsupdater
 > Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
 > Installed the plugin 'vagrant-hostsupdater (1.1.1.160)'!
 >
 > [harsxv@heiften ELK-stack-Digitalocean]$ vagrant ssh
 > Vagrant failed to initialize at a very early stage:
 > 
 > vagrant-hostsupdater missing, please install the plugin with this command:
 > vagrant plugin install vagrant-hostsupdater
 
I try to reinstall this plugins, but still have the same error.

> [harsxv@heiften ELK-stack-Digitalocean]$ vagrant plugin uninstall vagrant-hostsupdater
> Uninstalling the 'vagrant-hostsupdater' plugin...
> Successfully uninstalled vagrant-hostsupdater-1.1.1.160
>
> [harsxv@heiften ELK-stack-Digitalocean]$ vagrant plugin install vagrant-hostsupdater
> Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
> Fetching: vagrant-hostsupdater-1.1.1.160.gem (100%)
> Installed the plugin 'vagrant-hostsupdater (1.1.1.160)'!
>
> [harsxv@heiften ELK-stack-Digitalocean]$ vagrant ssh
> Vagrant failed to initialize at a very early stage:
> 
> vagrant-hostsupdater missing, please install the plugin with this command:
> vagrant plugin install vagrant-hostsupdater

I try to update this plugins, still have the same error.

> [harsxv@heiften ELK-stack-Digitalocean]$ vagrant plugin update vagrant-hostsupdater
> Updating plugins: vagrant-hostsupdater. This may take a few minutes...
> All plugins are up to date.
>
> [harsxv@heiften ELK-stack-Digitalocean-test]$ vagrant plugin list
> vagrant-digitalocean (0.9.3, global)
>  - Version Constraint: > 0
> vagrant-hostsupdater (1.1.1.160, global)
>  - Version Constraint: > 0
>
> [harsxv@heiften ELK-stack-Digitalocean]$ vagrant ssh
> Vagrant failed to initialize at a very early stage:
> 
> vagrant-hostsupdater missing, please install the plugin with this command:
> vagrant plugin install vagrant-hostsupdater

I sure that I never changed my Vagrantfile config or etc in directory this morning. Just update my Manjaro Linux with pamac.

Looking forward for any solutions. Thanks.

**Comment by harsxv** [comment]
Downgrading to `2.1.0` and problem fixed.

**Comment by Jeanvanberlo** [comment]
This plugin doesn't work since vagrant 2.1.3
