### ISSUE TITLE
1.2.3 hosts are no longer removed on destroy

### ISSUE THREAD

**Issue by skyscooby** [agiledivider/vagrant-hostsupdater#200]
Historically destroy of environment removes the /etc/hosts entries so they do not build up over time. Since 1.2.2 changes this is no longer hooking into the destroy sequence properly.

@BR0kEN- This is in follow up to #198. I mentioned it but it didn't get fixed with that fix but you can use the same Vagrantfile to reproduce

**1.2.1**
```
$ vagrant destroy -f
==> be1: Forcing shutdown of VM...
==> be1: Destroying VM and associated drives...
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> be1: [vagrant-hostsupdater] Removing hosts
==> fe1: Forcing shutdown of VM...
==> fe1: Destroying VM and associated drives...
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
==> fe1: [vagrant-hostsupdater] Removing hosts
```

**1.2.3**
```
$ vagrant destroy -f
==> be1: Forcing shutdown of VM...
==> be1: Destroying VM and associated drives...
==> fe1: Forcing shutdown of VM...
==> fe1: Destroying VM and associated drives...
```

**Comment by BR0kEN-** [comment]
The fix incorporated into 1.2.3 is not able to remove broken entries produced by 1.2.2. Please clean up `/etc/hosts` manually and do `vagrant up` and `vagrant destroy` once again.

**Comment by skyscooby** [comment]
Cleaned up manually and retried.. still the same, the plugin is not being called on destroy.

I suspect this is due to the fact you are using a Class Variable @@completed that is shared across all descendants of the class. This variable should probably be defined in each 'Action' explicitly so they each get their own state management and would allow each to run once per machine.

**Comment by skyscooby** [comment]
Alternatively @@completed needs to not just be keyed by machine but also by the action being requested.
